language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

env:
  - BTYPE="Debug"
  - BTYPE="Release"

before_install:
  # Get a good libcurl
  - curl http://curl.haxx.se/download/curl-7.43.0.tar.gz | tar -xzf -
  - cd curl-7.43.0
  - ./configure --with-ssl
  - make && sudo make install
  - cd ..
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y lcov
  # install gcc 4.8 and update alternatives
  - if [ ${CXX} = "g++" ]; then sudo apt-get install -y gcc-4.8 g++-4.8; fi
  - if [ ${CXX} = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  # install CMake 3.2.2
  - curl http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -
  - cd cmake-3.2.2
  - (./bootstrap && sudo make install -j6) &> /dev/null
  - cd ../ && rm -fr cmake-3.2.2

script:
  - echo y | tools/build $BTYPE

after_success:
  - if [ ${BTYPE} = "Release" ]; then tools/test_on_install Release; fi

